In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
# roc curve and auc score
from sklearn.datasets import make_classification

Select the Right Threshold values using ROC Curve

In [2]:
from sklearn.model_selection import train_test_split
X, y = make_classification(n_samples=2000, n_classes=2, weights=[1,1], random_state=1)

In [3]:
X.shape

(2000, 20)

In [4]:
y

array([0, 0, 0, ..., 1, 1, 0])

In [5]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(X, y, test_size=0.3, random_state=1)

In [7]:
from sklearn.metrics import roc_curve
from sklearn.metrics import roc_auc_score

In [8]:
## Apply RandomForestClassifier
from sklearn.ensemble import RandomForestClassifier
rf_model = RandomForestClassifier()
rf_model.fit(X_train, y_train)
ytrain_pred = rf_model.predict_proba(X_train)
print('RF train roc-auc: {}'.format(roc_auc_score(y_train, ytrain_pred[:,1])))
ytest_pred = rf_model.predict_proba(X_test)
print('RF test roc-auc: {}'.format(roc_auc_score(y_test, ytest_pred[:,1])))

RF train roc-auc: 1.0
RF test roc-auc: 0.9811166666666666


In [9]:
ytrain_pred

array([[1.  , 0.  ],
       [0.96, 0.04],
       [0.02, 0.98],
       ...,
       [0.97, 0.03],
       [0.96, 0.04],
       [0.24, 0.76]])

In [10]:
from sklearn.linear_model import LogisticRegression
log_classifier=LogisticRegression()
log_classifier.fit(X_train, y_train)
ytrain_pred = log_classifier.predict_proba(X_train)
print('Logistic train roc-auc: {}'.format(roc_auc_score(y_train, ytrain_pred[:,1])))
ytest_pred = log_classifier.predict_proba(X_test)
print('Logistic test roc-auc: {}'.format(roc_auc_score(y_test, ytest_pred[:,1])))

Logistic train roc-auc: 0.9863568922694498
Logistic test roc-auc: 0.9885777777777777


In [13]:
from sklearn.ensemble import AdaBoostClassifier
ada_classifier=AdaBoostClassifier()
ada_classifier.fit(X_train, y_train)
ytrain_pred = ada_classifier.predict_proba(X_train)
print('Adaboost train roc-auc: {}'.format(roc_auc_score(y_train, ytrain_pred[:,1])))
ytest_pred = ada_classifier.predict_proba(X_test)
print('Adaboost test roc-auc: {}'.format(roc_auc_score(y_test, ytest_pred[:,1])))

Adaboost train roc-auc: 0.9975081174960356
Adaboost test roc-auc: 0.9826111111111111


In [14]:
from sklearn.neighbors import KNeighborsClassifier
knn_classifier=KNeighborsClassifier()
knn_classifier.fit(X_train, y_train)
ytrain_pred = knn_classifier.predict_proba(X_train)
print('Adaboost train roc-auc: {}'.format(roc_auc_score(y_train, ytrain_pred[:,1])))
ytest_pred = knn_classifier.predict_proba(X_test)
print('Adaboost test roc-auc: {}'.format(roc_auc_score(y_test, ytest_pred[:,1])))

Adaboost train roc-auc: 0.981670071491109
Adaboost test roc-auc: 0.9426111111111111


In [15]:
#Now we will focus on selecting the best threshold for maximum accuracy
pred=[]
for model in [rf_model,log_classifier,ada_classifier,knn_classifier]:
    pred.append(pd.Series(model.predict_proba(X_test)[:,1]))
final_prediction=pd.concat(pred,axis=1).mean(axis=1)
print('Ensemble test roc-auc: {}'.format(roc_auc_score(y_test,final_prediction)))

Ensemble test roc-auc: 0.9843555555555554


In [16]:
pd.concat(pred,axis=1)

0         1         2    3
0    0.99  0.991861  0.559186  1.0
1    0.01  0.000008  0.463282  0.0
2    1.00  0.966929  0.538202  0.8
3    0.94  0.761539  0.509875  0.8
4    0.64  0.779443  0.490344  0.4
..    ...       ...       ...  ...
595  0.02  0.024239  0.461121  0.0
596  0.02  0.000003  0.441377  0.0
597  0.99  0.984385  0.532403  1.0
598  0.01  0.001147  0.441720  0.2
599  0.98  0.989540  0.559890  0.8

[600 rows x 4 columns]

In [17]:
final_prediction

0      0.885262
1      0.118323
2      0.826283
3      0.752853
4      0.577447
         ...   
595    0.126340
596    0.115345
597    0.876697
598    0.163217
599    0.832357
Length: 600, dtype: float64

In [18]:
#### Calculate the ROc Curve

fpr, tpr, thresholds = roc_curve(y_test, final_prediction)
thresholds

array([1.90938114, 0.90938114, 0.90422166, 0.90327475, 0.81139369,
       0.8105558 , 0.80225303, 0.80162833, 0.78387064, 0.78321156,
       0.77242916, 0.77037124, 0.7266922 , 0.72637362, 0.70971721,
       0.70893711, 0.6717442 , 0.66993537, 0.61238185, 0.59550386,
       0.58745356, 0.57925354, 0.57646627, 0.57486186, 0.56406376,
       0.56389283, 0.54365858, 0.52377948, 0.52105932, 0.48116892,
       0.4396034 , 0.37975652, 0.37629719, 0.35568654, 0.35086612,
       0.23717239, 0.23390421, 0.20666474, 0.20598417, 0.11788782,
       0.1178351 , 0.10632697])

In [19]:
from sklearn.metrics import accuracy_score
accuracy_ls = []
for thres in thresholds:
    y_pred = np.where(final_prediction>thres,1,0)
    accuracy_ls.append(accuracy_score(y_test, y_pred, normalize=True))
    
accuracy_ls = pd.concat([pd.Series(thresholds), pd.Series(accuracy_ls)],
                        axis=1)
accuracy_ls.columns = ['thresholds', 'accuracy']
accuracy_ls.sort_values(by='accuracy', ascending=False, inplace=True)
accuracy_ls.head()

thresholds  accuracy
30    0.439603  0.961667
29    0.481169  0.958333
27    0.523779  0.958333
26    0.543659  0.958333
28    0.521059  0.956667

In [20]:
accuracy_ls

thresholds  accuracy
30    0.439603  0.961667
29    0.481169  0.958333
27    0.523779  0.958333
26    0.543659  0.958333
28    0.521059  0.956667
25    0.563893  0.955000
24    0.564064  0.953333
23    0.574862  0.951667
22    0.576466  0.950000
21    0.579254  0.948333
31    0.379757  0.946667
20    0.587454  0.946667
32    0.376297  0.945000
18    0.612382  0.943333
33    0.355687  0.943333
19    0.595504  0.943333
34    0.350866  0.941667
17    0.669935  0.935000
16    0.671744  0.933333
15    0.708937  0.920000
14    0.709717  0.918333
13    0.726374  0.910000
12    0.726692  0.908333
36    0.233904  0.876667
35    0.237172  0.876667
37    0.206665  0.848333
38    0.205984  0.846667
11    0.770371  0.846667
10    0.772429  0.845000
9     0.783212  0.833333
8     0.783871  0.831667
7     0.801628  0.810000
6     0.802253  0.808333
5     0.810556  0.793333
4     0.811394  0.791667
39    0.117888  0.595000
40    0.117835  0.593333
3     0.903275  0.511667
2     0.904222  0.510000
41    0.106327  0.501667
1     0.909381  0.500000
0     1.909381  0.500000

In [21]:

def plot_roc_curve(fpr, tpr):
    plt.plot(fpr, tpr, color='orange', label='ROC')
    plt.plot([0, 1], [0, 1], color='darkblue', linestyle='--')
    plt.xlabel('False Positive Rate')
    plt.ylabel('True Positive Rate')
    plt.title('Receiver Operating Characteristic (ROC) Curve')
    plt.legend()
    plt.show()